# Generated by Django 5.0.6 on 2024-06-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floplegends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floplegendsmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
