databases:
  - name: superbase
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: flopProject
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn flopProject.wsgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: superbase
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4